export function renderDemoPage() {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Team SaaS starter</title>
<style>:root{color-scheme:dark;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;background:#080b10;color:#e8edf2}body{max-width:920px;margin:0 auto;padding:48px 20px}h1{font-size:clamp(2rem,7vw,4.5rem);margin:0 0 12px;letter-spacing:-.06em}p{color:#9aa7b5;line-height:1.6}.bar,section{border:1px solid #26313d;background:#10161d;border-radius:12px;padding:16px;margin:16px 0}.bar,form{display:flex;gap:10px;flex-wrap:wrap;align-items:center}button,input,select{font:inherit;color:inherit;background:#080b10;border:1px solid #344252;border-radius:8px;padding:10px 12px}button{background:#b7ff5a;color:#10160a;border-color:#b7ff5a;cursor:pointer;font-weight:700}button.secondary{background:transparent;color:#e8edf2;border-color:#526274}input{flex:1;min-width:220px}pre{min-height:260px;overflow:auto;white-space:pre-wrap;color:#b7ff5a}</style></head>
<body><h1>Tenant boundaries you can see.</h1><p>Switch identities, attempt writes, run retryable work, and inspect tenant-scoped audit history. Identity headers are a local teaching adapter, not production authentication.</p>
<div class="bar"><label>User <select id="identity"><option value="acme:alice">Acme · Alice · owner</option><option value="acme:sam">Acme · Sam · member</option><option value="acme:viv">Acme · Viv · viewer</option><option value="globex:bob">Globex · Bob · owner</option><option value="globex:gina">Globex · Gina · member</option></select></label><button data-action="issues">List issues</button><button class="secondary" data-action="audit">Audit log</button><button class="secondary" data-action="dead">Dead letters</button></div>
<section><form id="issue-form"><input id="title" value="Customer cannot export report" maxlength="160"><button>Create issue</button></form></section>
<section><form id="job-form"><input id="key" value="daily-digest-2026-09-09" maxlength="100"><button>Queue digest</button><button type="button" class="secondary" data-action="run">Run next job</button></form></section>
<section><pre id="output">Choose an action.</pre></section>
<script>const output=document.querySelector('#output');const identity=()=>{const[tenantId,userId]=document.querySelector('#identity').value.split(':');return{'x-tenant-id':tenantId,'x-user-id':userId}};const request=async(path,options={})=>{const response=await fetch(path,{...options,headers:{'content-type':'application/json',...identity(),...options.headers}});const body=await response.json();output.textContent=JSON.stringify({status:response.status,body},null,2)};document.querySelector('[data-action="issues"]').onclick=()=>request('/api/issues');document.querySelector('[data-action="audit"]').onclick=()=>request('/api/audit');document.querySelector('[data-action="dead"]').onclick=()=>request('/api/dead-letters');document.querySelector('[data-action="run"]').onclick=()=>request('/api/jobs/run',{method:'POST',body:'{}'});document.querySelector('#issue-form').onsubmit=(event)=>{event.preventDefault();request('/api/issues',{method:'POST',body:JSON.stringify({title:document.querySelector('#title').value})})};document.querySelector('#job-form').onsubmit=(event)=>{event.preventDefault();request('/api/digests',{method:'POST',body:JSON.stringify({idempotencyKey:document.querySelector('#key').value})})};</script></body></html>`;
}
